version: "3.9"
services: 
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
    ports:
      - '5432:5432'
    volumes:
      - simple_bank_volume:/var/lib/postgresql/data
    networks:
      - simple_bank_net

  app:
    build: .
    volumes:
      - .:/usr/src/app
    networks:
      - simple_bank_net
  
volumes:
  simple_bank_volume:

networks:
  simple_bank_net:
    driver: bridge
